package com.parking.controller;

import com.parking.model.GarageSpot;
import com.parking.model.Ticket;
import com.parking.model.Vehicle;
import com.parking.repository.SpotRepository;
import com.parking.service.PricingService;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.verify;

import java.time.LocalDateTime;
import java.util.List;

@ExtendWith(MockitoExtension.class)
class GarageControllerTest {

    @Mock
    SpotRepository spotRepository;

    @Mock
    PricingService pricingService;

    GarageController controller;

    @BeforeEach
    void setUp() {
        controller = new GarageController(spotRepository, pricingService);
    }

    @Test
    void shouldInitializeSuccessfully() {
        assertNotNull(controller, "Controller should exist");
    }

    @Test
    void receiveTicketWhenSpotIsAvailable() {
        Vehicle car = new Vehicle("ABC 111", "Lexus", "LFA", "White");
        GarageSpot emptySpot = new GarageSpot(1);

        // Use mock to simulate available spot
        when(spotRepository.findAvailableSpots()).thenReturn(List.of(emptySpot));

        GarageSpot spot = controller.enterCar(car);

        assertNotNull(spot, "Should receive a spot");
        assertNotNull(spot.getTicket(), "Spot should have a ticket");
    }

    @Test
    void rejectEntryWhenNoSpotsAvailable() {
        Vehicle car = new Vehicle("ABC 121", "Ford", "Mustang", "Red");

        // We tell the mock repository to return no available spots
        when(spotRepository.findAvailableSpots()).thenReturn(java.util.Collections.emptyList());

        GarageSpot spot = controller.enterCar(car);

        assertNull(spot, "Should NOT receive a spot when full");
    }

    @Test
    void shouldAllowExitWhenVehicleIsParked() {
        GarageSpot occupiedSpot = new GarageSpot(1);
        Ticket ticket = new Ticket(LocalDateTime.now().minusHours(1));
        occupiedSpot.occupy(new Vehicle("ABC 121", "Lexus", "LFA", "Red"), ticket);

        // We tell the mock repository to return the occupied spot when searched by ID
        when(spotRepository.findById(1)).thenReturn(occupiedSpot);

        when(pricingService.calculatePrice(any(), any())).thenReturn(50.0);

        // Now we try to exit
        double price = controller.exitCar(1);

        assertTrue(price > 0, "Exit should return a price");
        assertTrue(occupiedSpot.isEmpty(), "Spot should now be empty");
    }

    @Test
    void shouldFailExitWhenSpotIsAlreadyEmpty() {
        GarageSpot emptySpot = new GarageSpot(2);
        
        // Mock the repository to return this empty spot
        when(spotRepository.findById(2)).thenReturn(emptySpot);

        double price = controller.exitCar(2);

        assertEquals(-1.0, price, 0.01, "Should return -1.0 because spot was already empty");
    }

    @Test
    void shouldFailExitWhenSpotDoesNotExist() {
        when(spotRepository.findById(99)).thenReturn(null);

        double price = controller.exitCar(99);

        assertEquals(-1.0, price, 0.01, "Should return -1.0 for unknown spot ID"); // spot does not exist
    }

    @Test
    void shouldSaveTicketInSpotWhenParking() {
        Vehicle car = new Vehicle("ABC 121", "Tesla", "X", "White");
        GarageSpot spot = new GarageSpot(1);

        // We tell mock to return our real spot
        when(spotRepository.findAvailableSpots()).thenReturn(List.of(spot));

        GarageSpot returnedSpot = controller.enterCar(car);

        assertNotNull(returnedSpot);
        assertNotNull(returnedSpot.getTicket(), "Spot should have a ticket");
        // It checks that the ticket generated by the controller is stored in the spot
        assertEquals(car, returnedSpot.getParkedVehicle(), "The vehicle should be parked in the spot");
    }

    @Test
    void shouldReturnCalculatedPriceWhenExitingWithTicket() {
        GarageSpot spot = new GarageSpot(1);
        Vehicle car = new Vehicle("ABC 111", "Car", "X", "Red");
        Ticket ticket = new Ticket(LocalDateTime.now().minusHours(3));
        spot.occupy(car, ticket);

        when(spotRepository.findById(1)).thenReturn(spot);

        double fakePrice = 999.0; // We define a fake price for testing
        when(pricingService.calculatePrice(any(), any())).thenReturn(fakePrice);

        double price = controller.exitCar(1);

        // We expect the controller to return the price given by the PricingService
        assertEquals(999.0, price, 0.01, "Controller should simply return the value from PricingService");
        
        verify(pricingService).calculatePrice(any(), any());
    }

    @Test
    void shouldCalculatePriceForSpecificExitTime() {
        GarageSpot spot = new GarageSpot(1);
        Ticket ticket = new Ticket(LocalDateTime.now().minusHours(5)); // I entered 5 hours ago
        spot.occupy(new Vehicle("ABC 123", "Car", "X", "Red"), ticket);

        when(spotRepository.findById(1)).thenReturn(spot);
        
        // We simulate a time 10 hours in the future
        LocalDateTime futureExitTime = LocalDateTime.now().plusHours(10);
        
        // I basically tell the mock pricing service to return 100.0 when called
        when(pricingService.calculatePrice(any(), any())).thenReturn(100.0);

        double price = controller.exitCar(1, futureExitTime);

        assertEquals(100.0, price);
        
        // verify that the pricing service was called with the correct times
        verify(pricingService).calculatePrice(eq(ticket.getEntryTime()), eq(futureExitTime));
    }
}